import {
  faGlassMartiniAlt as fasGlassMartiniAlt,
  faChevronRight as fasChevronRight,
  faWineGlassAlt as fasWineGlassAlt,
  faGlassWhiskey as fasGlassWhiskey,
  faCocktail as fasCocktail,
  faBookOpen as fasBookOpen,
  faUtensils as fasUtensil,
  faHeart as fasHeart,
  faHome as fasHome,
  faBook as fasBook,
  faGlassCheers as fasGlassCheers,
  faWineGlass as fasWineGlass,
  faWineBottle as fasWineBottle,
  faBlender as fasBlender,
  faBeer as fasBeer,
  faFlask as fasFlask,
  faCoffee as fasCoffee,
  faMugHot as fasMugHot,
  faLongArrowAltLeft as fasLongArrowAltLeft,
  faGraduationCap,
  faTimes as fasTimes,
  faStar as fasStar,
} from '@fortawesome/free-solid-svg-icons';

import { faHeart as farHeart, faStar as farStar } from '@fortawesome/free-regular-svg-icons';

export default {
  //Solid
  fasUtensil,
  fasBookOpen,
  fasHeart,
  fasChevronRight,
  fasCocktail,
  fasWineGlassAlt,
  fasGlassMartiniAlt,
  fasGlassWhiskey,
  fasHome,
  fasBook,
  fasGlassCheers,
  fasWineBottle,
  fasWineGlass,
  fasBlender,
  fasBeer,
  fasFlask,
  fasCoffee,
  fasMugHot,
  fasLongArrowAltLeft,
  faGraduationCap,
  fasTimes,
  fasStar,

  //Regular
  farHeart,
  farStar,
};
